server:
  port: 8888

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST 

zuul:
  routes:
    consultants:
      path: /api/v1/consultants/**
      sensitiveHeaders: 
      serviceId: consultants
    clients:
      path: /api/v1/clients/**
      sensitiveHeaders: 
      serviceId: clients
    categories:
      path: /api/v1/categories/**
      sensitiveHeaders: 
      serviceId: categories
    skills:
      path: /api/v1/skills/**
      sensitiveHeaders: 
      serviceId: skills
    sites:
      path: /api/v1/sites/**
      sensitiveHeaders: 
      serviceId: sites
    projects:
      path: /api/v1/projects/**
      sensitiveHeaders: 
      serviceId: projects
    teams:
      path: /api/v1/teams/**
      sensitiveHeaders: 
      serviceId: teams
    leaders:
      path: /api/v1/leaders/**
      sensitiveHeaders: 
      serviceId: leaders
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 100000
                        
            timeout:
              enabled: false     
              
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 200000   

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:8761/eureka/
      
spring:
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
