server:
  port: 50001
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: consultants
      host: localhost
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
categories:
  service: CATEGORIES
  
projects:
  service: PROJECTS
  
expertises:
  service: EXPERTISES

sites:
  service: SITES
    
management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
