server:
  port: 8888

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST 

zuul:
  routes:
    planes:
      path: /api/v1/planes/**
      sensitiveHeaders: 
      serviceId: planes
    flights:
      path: /api/v1/flights/**
      sensitiveHeaders: 
      serviceId: flights
    fares:
      path: /api/v1/fares/**
      sensitiveHeaders: 
      serviceId: fares
    passengers:
      path: /api/v1/passengers/**
      sensitiveHeaders: 
      serviceId: passengers
    payments:
      path: /api/v1/payments/**
      sensitiveHeaders: 
      serviceId: payments
    auth:
      path: /api/v1/auth/**
      sensitiveHeaders: 
      serviceId: auth    
    bookings:
      path: /api/v1/bookings/**
      sensitiveHeaders:
      serviceId: bookings
    ecommerce:
      path: /api/v1/ecommerce/**
      sensitiveHeaders:
      serviceId: ecommerce
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
                        
            timeout:
              enabled: false     
              
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 20000
    
proxy:
  auth:
    routes:
      planes: oauth2
      flighst: oauth2
      fares: oauth2
      bookings: oauth2
      payments: oauth2
      passengers: oauth2
      ecommerce: oauth2

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:8761/eureka/
      
spring:
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true      
